CREATE TABLE admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_admin_user_username UNIQUE (username),
    CONSTRAINT ck_admin_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_ciphertext BYTEA NOT NULL,
    phone_hmac VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255),
    status VARCHAR(40) NOT NULL,
    created_by_admin_id BIGINT NOT NULL,
    activated_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_account_phone_hmac UNIQUE (phone_hmac),
    CONSTRAINT fk_user_account_creator FOREIGN KEY (created_by_admin_id) REFERENCES admin_user (id),
    CONSTRAINT ck_user_account_status CHECK (
        status IN ('PAID_PENDING_ACTIVATION', 'ACTIVE', 'SUSPENDED', 'CLOSED')
    ),
    CONSTRAINT ck_user_account_password_state CHECK (
        (status = 'PAID_PENDING_ACTIVATION' AND password_hash IS NULL)
        OR (status <> 'PAID_PENDING_ACTIVATION' AND password_hash IS NOT NULL)
    )
);

CREATE TABLE external_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    subject_ciphertext BYTEA NOT NULL,
    subject_hmac VARCHAR(64) NOT NULL,
    union_id_ciphertext BYTEA,
    union_id_hmac VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_external_identity_account FOREIGN KEY (user_account_id) REFERENCES user_account (id),
    CONSTRAINT uq_external_identity_subject UNIQUE (provider, subject_hmac),
    CONSTRAINT uq_external_identity_account_provider UNIQUE (user_account_id, provider),
    CONSTRAINT ck_external_identity_provider CHECK (provider IN ('WECHAT')),
    CONSTRAINT ck_external_identity_union_pair CHECK (
        (union_id_ciphertext IS NULL AND union_id_hmac IS NULL)
        OR (union_id_ciphertext IS NOT NULL AND union_id_hmac IS NOT NULL)
    )
);

CREATE TABLE payment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    payment_reference VARCHAR(100) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    status VARCHAR(24) NOT NULL DEFAULT 'PAID',
    paid_at TIMESTAMPTZ NOT NULL,
    operator_admin_id BIGINT NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_record_account FOREIGN KEY (user_account_id) REFERENCES user_account (id),
    CONSTRAINT fk_payment_record_operator FOREIGN KEY (operator_admin_id) REFERENCES admin_user (id),
    CONSTRAINT uq_payment_record_reference UNIQUE (payment_reference),
    CONSTRAINT ck_payment_record_amount CHECK (amount_minor > 0),
    CONSTRAINT ck_payment_record_currency CHECK (currency = 'CNY'),
    CONSTRAINT ck_payment_record_status CHECK (status IN ('PAID', 'REFUNDED'))
);

CREATE TABLE activation_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    credential_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_by_admin_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activation_credential_account FOREIGN KEY (user_account_id) REFERENCES user_account (id),
    CONSTRAINT fk_activation_credential_creator FOREIGN KEY (created_by_admin_id) REFERENCES admin_user (id),
    CONSTRAINT ck_activation_credential_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_activation_credential_consumed CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE UNIQUE INDEX uq_activation_credential_unconsumed
    ON activation_credential (user_account_id)
    WHERE consumed_at IS NULL;

CREATE INDEX ix_activation_credential_expiry
    ON activation_credential (expires_at)
    WHERE consumed_at IS NULL;

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type VARCHAR(24) NOT NULL,
    actor_id BIGINT,
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(100) NOT NULL,
    target_id BIGINT,
    request_id VARCHAR(64),
    metadata TEXT NOT NULL DEFAULT '{}',
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_audit_log_actor_type CHECK (actor_type IN ('ADMIN', 'GUEST', 'SYSTEM')),
    CONSTRAINT ck_audit_log_actor_id CHECK (
        (actor_type = 'SYSTEM' AND actor_id IS NULL)
        OR (actor_type <> 'SYSTEM' AND actor_id IS NOT NULL)
    )
);

CREATE INDEX ix_audit_log_target ON audit_log (target_type, target_id, occurred_at DESC);
CREATE INDEX ix_audit_log_actor ON audit_log (actor_type, actor_id, occurred_at DESC);

CREATE FUNCTION reject_audit_log_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_log rows are immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_immutable
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION reject_audit_log_mutation();
