-- 婚恋智能档案库：完整数据库结构。
--
-- 免费自助注册（手机号 + 密码）→ 档案保存即生效 → 付费或激活码升级 VIP。
-- 除密码之外的字段一律明文存储；密码只存 Argon2id 摘要，永不可逆。
-- Flyway 以 archive_owner 执行；运行时账号 archive_app 没有 DDL 权限，
-- 授权集中在文件末尾，新增表必须在那里显式授权。

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ==========================================================================
-- 管理员
-- ==========================================================================

CREATE TABLE admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_admin_user_username UNIQUE (username),
    CONSTRAINT ck_admin_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

-- ==========================================================================
-- 账号与会员
-- ==========================================================================

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(11) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    membership_tier VARCHAR(16) NOT NULL DEFAULT 'FREE',
    membership_credit_minor BIGINT NOT NULL DEFAULT 0,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_account_phone UNIQUE (phone),
    -- 位数校验同时钉在库里，应用层不是唯一防线。
    CONSTRAINT ck_user_account_phone CHECK (phone ~ '^1[3-9][0-9]{9}$'),
    CONSTRAINT ck_user_account_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    CONSTRAINT ck_user_account_tier CHECK (membership_tier IN ('FREE', 'VIP', 'SVIP')),
    CONSTRAINT ck_user_account_credit CHECK (membership_credit_minor >= 0)
);

-- 激活码在生成时就绑定手机号，只有该手机号的账号能兑换。
-- code 明文存储：管理员必须能复读并分发给对应用户。
CREATE TABLE activation_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL,
    bound_phone VARCHAR(11) NOT NULL,
    granted_tier VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'UNUSED',
    redeemed_by_account_id BIGINT REFERENCES user_account (id),
    redeemed_at TIMESTAMPTZ,
    created_by_admin_id BIGINT NOT NULL REFERENCES admin_user (id),
    note VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_activation_code UNIQUE (code),
    CONSTRAINT ck_activation_code_phone CHECK (bound_phone ~ '^1[3-9][0-9]{9}$'),
    CONSTRAINT ck_activation_code_tier CHECK (granted_tier IN ('VIP', 'SVIP')),
    CONSTRAINT ck_activation_code_status CHECK (status IN ('UNUSED', 'USED', 'REVOKED')),
    CONSTRAINT ck_activation_code_used_shape CHECK (
        status <> 'USED'
        OR (redeemed_by_account_id IS NOT NULL AND redeemed_at IS NOT NULL)
    )
);

CREATE INDEX ix_activation_code_phone ON activation_code (bound_phone, created_at DESC);
CREATE INDEX ix_activation_code_status ON activation_code (status, created_at DESC);

-- ==========================================================================
-- 授权书与同意记录
-- ==========================================================================

CREATE TABLE authorization_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code VARCHAR(64) NOT NULL,
    version VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    effective_at TIMESTAMPTZ NOT NULL,
    created_by_admin_id BIGINT REFERENCES admin_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_authorization_document_code_version UNIQUE (document_code, version)
);

CREATE UNIQUE INDEX uq_authorization_document_active
    ON authorization_document (document_code) WHERE status = 'ACTIVE';
CREATE INDEX ix_authorization_document_creator
    ON authorization_document (created_by_admin_id);

-- 注册时勾选同意即写入一条，只追加不可改。
-- expires_at 仍记录一年期限用于留痕，但不再作为访问档案的前置条件。
CREATE TABLE authorization_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES user_account (id),
    authorization_document_id BIGINT NOT NULL REFERENCES authorization_document (id),
    accepted BOOLEAN NOT NULL CHECK (accepted),
    accepted_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL CHECK (expires_at = effective_at + INTERVAL '1 year'),
    source_page VARCHAR(64) NOT NULL,
    client_ip VARCHAR(45),
    user_agent VARCHAR(500),
    session_reference VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_authorization_record_effective_at CHECK (effective_at = accepted_at)
);

CREATE INDEX ix_authorization_record_account
    ON authorization_record (user_account_id, authorization_document_id, expires_at DESC);
CREATE INDEX ix_authorization_record_document
    ON authorization_record (authorization_document_id);

-- ==========================================================================
-- 支付：付费只用于升级 VIP，付款人一定是已登录账号
-- ==========================================================================

CREATE TABLE payment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES user_account (id),
    out_trade_no VARCHAR(64) NOT NULL,
    transaction_id VARCHAR(64) NOT NULL,
    channel VARCHAR(24) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    status VARCHAR(16) NOT NULL DEFAULT 'PAID',
    -- 会员额度累计的幂等锚点：同一笔付款只能计入一次。
    membership_credit_minor BIGINT NOT NULL DEFAULT 0,
    paid_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payment_record_out_trade_no UNIQUE (out_trade_no),
    CONSTRAINT uq_payment_record_transaction_id UNIQUE (transaction_id),
    CONSTRAINT ck_payment_record_channel CHECK (channel = 'XPAY_ALIPAY'),
    CONSTRAINT ck_payment_record_amount CHECK (amount_minor > 0),
    CONSTRAINT ck_payment_record_currency CHECK (currency = 'CNY'),
    CONSTRAINT ck_payment_record_status CHECK (status IN ('PAID', 'REFUNDED')),
    CONSTRAINT ck_payment_record_credit CHECK (
        membership_credit_minor >= 0 AND membership_credit_minor <= amount_minor
    )
);

CREATE INDEX ix_payment_record_account ON payment_record (user_account_id, paid_at DESC);

-- out_trade_no 由服务端随机生成，全局唯一，是渠道回调的幂等锚点。
CREATE TABLE payment_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    out_trade_no VARCHAR(64) NOT NULL,
    user_account_id BIGINT NOT NULL REFERENCES user_account (id),
    channel VARCHAR(24) NOT NULL,
    amount_minor BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    transaction_id VARCHAR(64),
    paid_at TIMESTAMPTZ,
    payment_record_id BIGINT REFERENCES payment_record (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_payment_order_out_trade_no UNIQUE (out_trade_no),
    CONSTRAINT ck_payment_order_channel CHECK (channel = 'XPAY_ALIPAY'),
    CONSTRAINT ck_payment_order_status CHECK (status IN ('CREATED', 'PAID', 'CLOSED')),
    CONSTRAINT ck_payment_order_amount CHECK (amount_minor > 0),
    CONSTRAINT ck_payment_order_paid_shape CHECK (
        status <> 'PAID'
        OR (transaction_id IS NOT NULL AND paid_at IS NOT NULL AND payment_record_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_payment_order_transaction_id
    ON payment_order (transaction_id) WHERE transaction_id IS NOT NULL;
CREATE INDEX ix_payment_order_account ON payment_order (user_account_id, created_at DESC);
CREATE INDEX ix_payment_order_status ON payment_order (status, created_at DESC);

-- ==========================================================================
-- 档案：保存即生效，没有审核与版本快照
-- ==========================================================================

CREATE TABLE guest_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_no UUID NOT NULL,
    user_account_id BIGINT NOT NULL REFERENCES user_account (id),
    gender VARCHAR(32),
    birth_date DATE,
    height_cm INTEGER,
    education VARCHAR(100),
    occupation VARCHAR(200),
    income_range VARCHAR(100),
    city VARCHAR(100),
    wechat_id VARCHAR(100),
    douyin_id VARCHAR(100),
    douyin_nickname VARCHAR(200),
    douyin_profile_url VARCHAR(500),
    -- 只区分「填完了没」，保存时按必填字段 + 头像算出来，供管理端列表筛选。
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_guest_profile_no UNIQUE (profile_no),
    CONSTRAINT uq_guest_profile_account UNIQUE (user_account_id),
    CONSTRAINT ck_guest_profile_status CHECK (status IN ('DRAFT', 'COMPLETED'))
);

CREATE INDEX ix_guest_profile_status ON guest_profile (status, updated_at DESC);

CREATE TABLE profile_field_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_code VARCHAR(64) NOT NULL,
    label VARCHAR(100) NOT NULL,
    storage_kind VARCHAR(16) NOT NULL,
    data_type VARCHAR(32) NOT NULL,
    required BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL,
    -- 单调标记：一旦有值引用过就不能再改字段编码与类型。
    ever_used BOOLEAN NOT NULL DEFAULT FALSE,
    options_json TEXT,
    sort_order INTEGER NOT NULL,
    instructions TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_field_definition_code UNIQUE (field_code),
    CONSTRAINT ck_profile_field_definition_storage_kind CHECK (storage_kind IN ('CORE', 'DYNAMIC')),
    CONSTRAINT ck_profile_field_definition_data_type CHECK (data_type IN (
        'TEXT', 'LONG_TEXT', 'INTEGER', 'DECIMAL', 'DATE', 'BOOLEAN', 'SINGLE_OPTION'
    ))
);

CREATE INDEX ix_profile_field_definition_enabled_sort
    ON profile_field_definition (enabled, sort_order);

CREATE TABLE profile_field_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_profile_id BIGINT NOT NULL REFERENCES guest_profile (id),
    field_definition_id BIGINT NOT NULL REFERENCES profile_field_definition (id),
    text_value TEXT,
    integer_value BIGINT,
    decimal_value NUMERIC(18, 2),
    date_value DATE,
    boolean_value BOOLEAN,
    option_value VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_field_value_profile_definition
        UNIQUE (guest_profile_id, field_definition_id),
    CONSTRAINT ck_profile_field_value_exactly_one_value CHECK (
        num_nonnulls(text_value, integer_value, decimal_value, date_value, boolean_value, option_value) = 1
    )
);

CREATE INDEX ix_profile_field_value_definition ON profile_field_value (field_definition_id);

-- 对象键只存服务端，不下发前端；预览地址每次按需签发，从不落库。
CREATE TABLE profile_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_profile_id BIGINT NOT NULL REFERENCES guest_profile (id),
    category VARCHAR(16) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_photo_object_key UNIQUE (object_key),
    CONSTRAINT uq_profile_photo_profile_category_sort
        UNIQUE (guest_profile_id, category, sort_order),
    CONSTRAINT ck_profile_photo_category CHECK (category IN ('AVATAR', 'LIFE'))
);

CREATE UNIQUE INDEX uq_profile_photo_avatar_one
    ON profile_photo (guest_profile_id) WHERE category = 'AVATAR';
CREATE INDEX ix_profile_photo_profile ON profile_photo (guest_profile_id);

-- ==========================================================================
-- 审计
-- ==========================================================================

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type VARCHAR(24) NOT NULL,
    actor_id BIGINT,
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(100) NOT NULL,
    target_id BIGINT,
    request_id VARCHAR(64),
    metadata TEXT NOT NULL DEFAULT '{}',
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_audit_log_actor_type CHECK (actor_type IN ('ADMIN', 'GUEST', 'SYSTEM')),
    CONSTRAINT ck_audit_log_actor_id CHECK (
        (actor_type = 'SYSTEM' AND actor_id IS NULL)
        OR (actor_type <> 'SYSTEM' AND actor_id IS NOT NULL)
    )
);

CREATE INDEX ix_audit_log_target ON audit_log (target_type, target_id, occurred_at DESC);
CREATE INDEX ix_audit_log_actor ON audit_log (actor_type, actor_id, occurred_at DESC);

-- ==========================================================================
-- 不可变与不变量
-- ==========================================================================

CREATE FUNCTION reject_row_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_immutable
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION reject_row_mutation();

CREATE TRIGGER authorization_record_immutable
    BEFORE UPDATE OR DELETE ON authorization_record
    FOR EACH ROW EXECUTE FUNCTION reject_row_mutation();

CREATE FUNCTION public.preserve_profile_field_definition_identity() RETURNS trigger AS $$
BEGIN
    IF OLD.storage_kind IS DISTINCT FROM NEW.storage_kind THEN
        RAISE EXCEPTION 'profile field definition storage kind is immutable';
    END IF;
    IF OLD.ever_used AND NOT NEW.ever_used THEN
        RAISE EXCEPTION 'profile field definition usage cannot be reset';
    END IF;
    IF OLD.ever_used AND (
        OLD.field_code IS DISTINCT FROM NEW.field_code
        OR OLD.data_type IS DISTINCT FROM NEW.data_type
    ) THEN
        RAISE EXCEPTION 'used profile field definition identity is immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
SET search_path = pg_catalog;

CREATE FUNCTION public.mark_profile_field_definition_ever_used() RETURNS trigger AS $$
BEGIN
    UPDATE public.profile_field_definition
    SET ever_used = TRUE
    WHERE id = NEW.field_definition_id AND NOT ever_used;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
SET search_path = pg_catalog;

CREATE TRIGGER profile_field_definition_identity_immutable
    BEFORE UPDATE ON public.profile_field_definition
    FOR EACH ROW EXECUTE FUNCTION public.preserve_profile_field_definition_identity();

CREATE TRIGGER profile_field_value_marks_definition_used
    BEFORE INSERT ON public.profile_field_value
    FOR EACH ROW EXECUTE FUNCTION public.mark_profile_field_definition_ever_used();

-- ==========================================================================
-- 运行时账号最小权限
-- ==========================================================================

GRANT USAGE ON SCHEMA public TO archive_app;

GRANT SELECT, INSERT, UPDATE
    ON admin_user, user_account, activation_code, payment_record, payment_order,
       guest_profile, profile_field_definition
    TO archive_app;

-- 草稿里的字段值与照片可以被覆盖或删除。
GRANT SELECT, INSERT, UPDATE, DELETE ON profile_field_value, profile_photo TO archive_app;

-- 只追加：授权书由管理员通过迁移维护，同意记录与审计日志不可改。
GRANT SELECT ON authorization_document TO archive_app;
GRANT SELECT, INSERT ON authorization_record TO archive_app;
GRANT SELECT, INSERT ON audit_log TO archive_app;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO archive_app;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM archive_app;
REVOKE UPDATE, DELETE, TRUNCATE ON audit_log FROM archive_app;
REVOKE UPDATE, DELETE, TRUNCATE ON authorization_record FROM archive_app;

-- ==========================================================================
-- 种子数据
-- ==========================================================================

-- 授权书正文沿用原有的数据使用条款，只去掉「付费才能建档」的表述——
-- 建档现在免费，付费只用于会员升级，原文的付款前置说法已不成立。
WITH seed AS (
    SELECT
        'PROFILE_LIVE_CONTENT'::VARCHAR(64) AS document_code,
        'v1.0'::VARCHAR(32) AS version,
        '档案与直播内容授权书'::VARCHAR(200) AS title,
        $$我已阅读并同意《档案与直播内容授权书》。

我知悉并同意，平台提供的服务由婚恋档案建立与维护、朋友圈锐评直播机会，以及经去标识化处理后的直播内容和宣传素材使用共同组成。建立档案不收取费用；会员等级为可选的增值服务。

我同意平台收集、存储和使用本人提交的手机号、微信号、抖音号、个人资料、生活照片及与朋友圈锐评有关的信息；同意工作人员添加本人微信，在本人设置的可见范围内查看、筛选和整理朋友圈内容；同意平台对相关内容进行必要的截图、打码、裁剪和编辑，并用于朋友圈锐评直播、直播回顾、抖音短视频及与本平台婚恋服务直接相关的宣传素材。

平台在公开使用前，应当遮挡或删除本人真实姓名、手机号、微信号、抖音号、二维码、精确地址、工作单位、车牌及其他能够直接识别身份的信息，并对朋友圈中出现的其他人员头像、昵称、评论、照片及相关信息进行遮挡或裁剪。

我已知悉，即使完成打码和去标识化处理，公开直播仍可能存在被观众录屏、转发或根据内容间接识别的风险。

未经本授权书明确约定，平台不会出售本人的个人信息，也不会将相关资料用于与建档、朋友圈锐评和本平台婚恋服务宣传无关的用途。

本授权自本人注册时主动勾选同意之日起生效。本人可以联系管理员撤回对未来直播和素材使用的授权；撤回不影响撤回前已经依法完成的处理，后续账号和服务将按照服务协议办理终止或资料删除。$$::TEXT AS content
)
INSERT INTO authorization_document (
    document_code, version, title, content, content_sha256, status, effective_at
)
SELECT
    document_code,
    version,
    title,
    content,
    encode(digest(convert_to(content, 'UTF8'), 'sha256'), 'hex'),
    'ACTIVE',
    CURRENT_TIMESTAMP
FROM seed;

-- 核心字段定义（取值已是最终形态：年薪为滚动选项，社交账号四项在列）。
INSERT INTO profile_field_definition (
    field_code, label, storage_kind, data_type, required, enabled, options_json,
    sort_order, instructions
) VALUES
    ('gender', '性别', 'CORE', 'SINGLE_OPTION', TRUE, TRUE, '["男", "女"]', 10, '请选择性别'),
    ('birth_date', '出生日期', 'CORE', 'DATE', TRUE, TRUE, NULL, 20, '请选择出生日期'),
    ('height_cm', '身高（厘米）', 'CORE', 'INTEGER', TRUE, TRUE, NULL, 30, '请输入身高'),
    ('education', '学历', 'CORE', 'TEXT', TRUE, TRUE, NULL, 40, '请输入学历'),
    ('occupation', '职业', 'CORE', 'TEXT', TRUE, TRUE, NULL, 50, '请输入职业'),
    ('income_range', '年薪', 'CORE', 'SINGLE_OPTION', TRUE, TRUE,
        '["小于10万","10-20万","20-30万","30-50万","50-100万","100万以上","保密"]',
        60, '请选择年薪范围'),
    ('city', '所在城市', 'CORE', 'TEXT', TRUE, TRUE, NULL, 70, '请输入所在城市'),
    ('wechat_id', '微信号', 'CORE', 'TEXT', TRUE, TRUE, NULL, 80, '请输入微信号'),
    ('douyin_id', '抖音号', 'CORE', 'TEXT', FALSE, TRUE, NULL, 90, '选填，请输入抖音号'),
    ('douyin_nickname', '抖音昵称', 'CORE', 'TEXT', FALSE, TRUE, NULL, 100, '选填，请输入抖音昵称'),
    ('douyin_profile_url', '抖音主页链接', 'CORE', 'TEXT', FALSE, TRUE, NULL, 110,
        '选填，请输入抖音主页链接');
