CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE authorization_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code VARCHAR(64) NOT NULL,
    version VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    effective_at TIMESTAMPTZ NOT NULL,
    created_by_admin_id BIGINT REFERENCES admin_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_authorization_document_code_version UNIQUE (document_code, version)
);

CREATE UNIQUE INDEX uq_authorization_document_active
    ON authorization_document (document_code) WHERE status = 'ACTIVE';
CREATE INDEX ix_authorization_document_creator
    ON authorization_document (created_by_admin_id);

ALTER TABLE payment_record
    ADD COLUMN presented_authorization_document_id BIGINT
    REFERENCES authorization_document(id);

CREATE INDEX ix_payment_record_presented_authorization_document
    ON payment_record (presented_authorization_document_id);

CREATE TABLE authorization_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES user_account(id),
    authorization_document_id BIGINT NOT NULL REFERENCES authorization_document(id),
    accepted BOOLEAN NOT NULL CHECK (accepted),
    accepted_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL CHECK (expires_at = effective_at + INTERVAL '1 year'),
    source_page VARCHAR(64) NOT NULL,
    client_ip_hmac VARCHAR(64) NOT NULL,
    user_agent_sha256 CHAR(64) NOT NULL,
    session_reference_hmac VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_authorization_record_effective_at CHECK (effective_at = accepted_at)
);

CREATE INDEX ix_authorization_record_eligibility
    ON authorization_record (user_account_id, authorization_document_id, expires_at DESC);
CREATE INDEX ix_authorization_record_document
    ON authorization_record (authorization_document_id);

CREATE TABLE guest_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_no UUID NOT NULL,
    user_account_id BIGINT NOT NULL REFERENCES user_account(id),
    gender VARCHAR(32),
    birth_date DATE,
    height_cm INTEGER,
    education VARCHAR(100),
    occupation VARCHAR(200),
    income_range VARCHAR(100),
    city VARCHAR(100),
    wechat_id_ciphertext BYTEA,
    wechat_id_hmac VARCHAR(64),
    douyin_id_ciphertext BYTEA,
    douyin_id_hmac VARCHAR(64),
    douyin_nickname_ciphertext BYTEA,
    douyin_profile_url_ciphertext BYTEA,
    pending_revision_id BIGINT,
    current_approved_revision_id BIGINT,
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_guest_profile_no UNIQUE (profile_no),
    CONSTRAINT uq_guest_profile_account UNIQUE (user_account_id),
    CONSTRAINT ck_guest_profile_status CHECK (status IN (
        'DRAFT', 'PENDING_REVIEW', 'CHANGES_REQUESTED', 'APPROVED',
        'SUSPENDED', 'DELETION_PENDING', 'ANONYMIZED'
    )),
    CONSTRAINT ck_guest_profile_wechat_pair CHECK (
        (wechat_id_ciphertext IS NULL AND wechat_id_hmac IS NULL)
        OR (wechat_id_ciphertext IS NOT NULL AND wechat_id_hmac IS NOT NULL)
    ),
    CONSTRAINT ck_guest_profile_douyin_pair CHECK (
        (douyin_id_ciphertext IS NULL AND douyin_id_hmac IS NULL)
        OR (douyin_id_ciphertext IS NOT NULL AND douyin_id_hmac IS NOT NULL)
    )
);

CREATE INDEX ix_guest_profile_status ON guest_profile (status);

CREATE TABLE profile_field_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_code VARCHAR(64) NOT NULL,
    label VARCHAR(100) NOT NULL,
    storage_kind VARCHAR(16) NOT NULL,
    data_type VARCHAR(32) NOT NULL,
    required BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL,
    ever_used BOOLEAN NOT NULL DEFAULT FALSE,
    options_json TEXT,
    sort_order INTEGER NOT NULL,
    instructions TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_field_definition_code UNIQUE (field_code),
    CONSTRAINT ck_profile_field_definition_storage_kind CHECK (storage_kind IN ('CORE', 'DYNAMIC')),
    CONSTRAINT ck_profile_field_definition_data_type CHECK (data_type IN (
        'TEXT', 'LONG_TEXT', 'INTEGER', 'DECIMAL', 'DATE', 'BOOLEAN', 'SINGLE_OPTION'
    ))
);

CREATE INDEX ix_profile_field_definition_enabled_sort
    ON profile_field_definition (enabled, sort_order);

CREATE FUNCTION preserve_profile_field_definition_ever_used() RETURNS trigger AS $$
BEGIN
    IF OLD.ever_used AND NOT NEW.ever_used THEN
        RAISE EXCEPTION 'profile field definition usage cannot be reset';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION mark_profile_field_definition_ever_used() RETURNS trigger AS $$
BEGIN
    UPDATE profile_field_definition
    SET ever_used = TRUE
    WHERE id = NEW.field_definition_id AND NOT ever_used;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profile_field_definition_ever_used_monotonic
    BEFORE UPDATE ON profile_field_definition
    FOR EACH ROW EXECUTE FUNCTION preserve_profile_field_definition_ever_used();

CREATE TABLE profile_field_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_profile_id BIGINT NOT NULL REFERENCES guest_profile(id),
    field_definition_id BIGINT NOT NULL REFERENCES profile_field_definition(id),
    text_value TEXT,
    integer_value BIGINT,
    decimal_value NUMERIC(18, 2),
    date_value DATE,
    boolean_value BOOLEAN,
    option_value VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_field_value_profile_definition UNIQUE (guest_profile_id, field_definition_id),
    CONSTRAINT ck_profile_field_value_exactly_one_value CHECK (
        num_nonnulls(text_value, integer_value, decimal_value, date_value, boolean_value, option_value) = 1
    )
);

CREATE INDEX ix_profile_field_value_definition ON profile_field_value (field_definition_id);

CREATE TRIGGER profile_field_value_marks_definition_used
    BEFORE INSERT ON profile_field_value
    FOR EACH ROW EXECUTE FUNCTION mark_profile_field_definition_ever_used();

CREATE TABLE profile_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_profile_id BIGINT NOT NULL REFERENCES guest_profile(id),
    revision_number INTEGER NOT NULL,
    gender VARCHAR(32),
    birth_date DATE,
    height_cm INTEGER,
    education VARCHAR(100),
    occupation VARCHAR(200),
    income_range VARCHAR(100),
    city VARCHAR(100),
    wechat_id_ciphertext BYTEA,
    wechat_id_hmac VARCHAR(64),
    douyin_id_ciphertext BYTEA,
    douyin_id_hmac VARCHAR(64),
    douyin_nickname_ciphertext BYTEA,
    douyin_profile_url_ciphertext BYTEA,
    status VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    submitted_by_account_id BIGINT NOT NULL REFERENCES user_account(id),
    submitted_at TIMESTAMPTZ NOT NULL,
    review_deadline_at TIMESTAMPTZ NOT NULL,
    reviewed_at TIMESTAMPTZ,
    submission_key_hmac VARCHAR(64) NOT NULL,
    request_payload_sha256 CHAR(64) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_revision_number UNIQUE (guest_profile_id, revision_number),
    CONSTRAINT uq_profile_revision_submission_key UNIQUE (guest_profile_id, submission_key_hmac),
    CONSTRAINT ck_profile_revision_deadline CHECK (
        review_deadline_at = submitted_at + INTERVAL '24 hours'
    ),
    CONSTRAINT ck_profile_revision_wechat_pair CHECK (
        (wechat_id_ciphertext IS NULL AND wechat_id_hmac IS NULL)
        OR (wechat_id_ciphertext IS NOT NULL AND wechat_id_hmac IS NOT NULL)
    ),
    CONSTRAINT ck_profile_revision_douyin_pair CHECK (
        (douyin_id_ciphertext IS NULL AND douyin_id_hmac IS NULL)
        OR (douyin_id_ciphertext IS NOT NULL AND douyin_id_hmac IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_profile_revision_pending
    ON profile_revision (guest_profile_id) WHERE status = 'PENDING';
CREATE INDEX ix_profile_revision_submitter ON profile_revision (submitted_by_account_id);
CREATE INDEX ix_profile_revision_review_status_deadline
    ON profile_revision (status, review_deadline_at);

ALTER TABLE guest_profile
    ADD CONSTRAINT fk_guest_profile_pending_revision
    FOREIGN KEY (pending_revision_id) REFERENCES profile_revision(id),
    ADD CONSTRAINT fk_guest_profile_approved_revision
    FOREIGN KEY (current_approved_revision_id) REFERENCES profile_revision(id);

CREATE INDEX ix_guest_profile_pending_revision ON guest_profile (pending_revision_id);
CREATE INDEX ix_guest_profile_approved_revision ON guest_profile (current_approved_revision_id);

CREATE TABLE profile_revision_field_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_revision_id BIGINT NOT NULL REFERENCES profile_revision(id),
    field_code VARCHAR(64) NOT NULL,
    field_label VARCHAR(100) NOT NULL,
    data_type VARCHAR(32) NOT NULL,
    display_option VARCHAR(200),
    text_value TEXT,
    integer_value BIGINT,
    decimal_value NUMERIC(18, 2),
    date_value DATE,
    boolean_value BOOLEAN,
    option_value VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_revision_field_value_code UNIQUE (profile_revision_id, field_code),
    CONSTRAINT ck_profile_revision_field_value_data_type CHECK (data_type IN (
        'TEXT', 'LONG_TEXT', 'INTEGER', 'DECIMAL', 'DATE', 'BOOLEAN', 'SINGLE_OPTION'
    )),
    CONSTRAINT ck_profile_revision_field_value_exactly_one_value CHECK (
        num_nonnulls(text_value, integer_value, decimal_value, date_value, boolean_value, option_value) = 1
    )
);

CREATE INDEX ix_profile_revision_field_value_revision
    ON profile_revision_field_value (profile_revision_id);

CREATE TABLE profile_review_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_revision_id BIGINT NOT NULL REFERENCES profile_revision(id),
    reviewer_admin_id BIGINT NOT NULL REFERENCES admin_user(id),
    result VARCHAR(16) NOT NULL CHECK (result IN ('APPROVED', 'REJECTED')),
    reason_code VARCHAR(64),
    comment TEXT,
    reviewed_at TIMESTAMPTZ NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_review_record_revision UNIQUE (profile_revision_id),
    CONSTRAINT ck_profile_review_record_rejected_comment CHECK (
        result <> 'REJECTED' OR NULLIF(BTRIM(comment), '') IS NOT NULL
    )
);

CREATE INDEX ix_profile_review_record_reviewer ON profile_review_record (reviewer_admin_id);

CREATE FUNCTION reject_profile_consent_immutable_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION allow_profile_revision_review_update() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'profile_revision rows are immutable';
    END IF;
    IF (to_jsonb(NEW) - ARRAY['status', 'reviewed_at', 'version'])
            IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status', 'reviewed_at', 'version']) THEN
        RAISE EXCEPTION 'profile_revision only permits status, reviewed_at, and version updates';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER authorization_record_immutable
    BEFORE UPDATE OR DELETE ON authorization_record
    FOR EACH ROW EXECUTE FUNCTION reject_profile_consent_immutable_mutation();

CREATE TRIGGER profile_revision_review_only
    BEFORE UPDATE OR DELETE ON profile_revision
    FOR EACH ROW EXECUTE FUNCTION allow_profile_revision_review_update();

CREATE TRIGGER profile_revision_field_value_immutable
    BEFORE UPDATE OR DELETE ON profile_revision_field_value
    FOR EACH ROW EXECUTE FUNCTION reject_profile_consent_immutable_mutation();

CREATE TRIGGER profile_review_record_immutable
    BEFORE UPDATE OR DELETE ON profile_review_record
    FOR EACH ROW EXECUTE FUNCTION reject_profile_consent_immutable_mutation();

WITH seed AS (
    SELECT
        'PAID_PROFILE_LIVE_CONTENT'::VARCHAR(64) AS document_code,
        'v0.3'::VARCHAR(32) AS version,
        '付费建档与直播内容授权书'::VARCHAR(200) AS title,
        $$我已阅读并同意《付费建档与直播内容授权书》。

我知悉并同意，本次付费服务是由婚恋档案建立与维护、一次朋友圈锐评直播机会，以及经审核和去标识化处理后的直播内容和宣传素材使用共同组成的组合服务。

我同意平台收集、存储和使用本人提交的手机号、微信号、抖音号、个人资料、生活照片及与朋友圈锐评有关的信息；同意工作人员添加本人微信，在本人设置的可见范围内查看、筛选和整理朋友圈内容；同意平台对相关内容进行必要的截图、打码、裁剪和编辑，并用于一次朋友圈锐评直播、直播回顾、抖音短视频及与本平台婚恋服务直接相关的宣传素材。

平台在公开使用前，应当遮挡或删除本人真实姓名、手机号、微信号、抖音号、二维码、精确地址、工作单位、车牌及其他能够直接识别身份的信息，并对朋友圈中出现的其他人员头像、昵称、评论、照片及相关信息进行遮挡或裁剪。

我已知悉，即使完成打码和去标识化处理，公开直播仍可能存在被观众录屏、转发或根据内容间接识别的风险。

未经本授权书明确约定，平台不会出售本人的个人信息，也不会将相关资料用于与建档、朋友圈锐评和本平台婚恋服务宣传无关的用途。

本授权自本人主动勾选同意之日起生效，有效期为一年。授权到期后，本人可以重新查看并主动确认当时版本的授权书，以完成续期。如本人未续期，平台不得使用本人的原始资料制作新的直播、视频或宣传素材；授权有效期内已经发布的视频可以保留在原发布位置，但不得重新剪辑、重新发布或用于新的推广活动。

如不同意上述组合服务内容，将无法建立档案。平台应在本人付款前提供本授权说明，以便本人自主决定是否购买。本人可以联系管理员撤回对未来直播和素材使用的授权；撤回不影响撤回前已经依法完成的处理，后续账号和服务将按照服务协议办理终止、退款或资料删除。$$::TEXT AS content
)
INSERT INTO authorization_document (
    document_code, version, title, content, content_sha256, status, effective_at
)
SELECT
    document_code,
    version,
    title,
    content,
    encode(digest(convert_to(content, 'UTF8'), 'sha256'), 'hex'),
    'ACTIVE',
    CURRENT_TIMESTAMP
FROM seed;

INSERT INTO profile_field_definition (
    field_code, label, storage_kind, data_type, required, enabled, options_json, sort_order, instructions
) VALUES
    ('gender', '性别', 'CORE', 'SINGLE_OPTION', TRUE, TRUE, '["男", "女"]', 10, '请选择性别'),
    ('birth_date', '出生日期', 'CORE', 'DATE', TRUE, TRUE, NULL, 20, '请选择出生日期'),
    ('height_cm', '身高（厘米）', 'CORE', 'INTEGER', TRUE, TRUE, NULL, 30, '请输入身高'),
    ('education', '学历', 'CORE', 'TEXT', TRUE, TRUE, NULL, 40, '请输入学历'),
    ('occupation', '职业', 'CORE', 'TEXT', TRUE, TRUE, NULL, 50, '请输入职业'),
    ('income_range', '收入范围', 'CORE', 'TEXT', TRUE, TRUE, NULL, 60, '请输入收入范围'),
    ('city', '所在城市', 'CORE', 'TEXT', TRUE, TRUE, NULL, 70, '请输入所在城市');

GRANT SELECT ON authorization_document TO archive_app;
GRANT SELECT, INSERT ON authorization_record TO archive_app;
GRANT SELECT, INSERT, UPDATE ON guest_profile TO archive_app;
GRANT SELECT, INSERT, UPDATE ON profile_field_definition TO archive_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON profile_field_value TO archive_app;
GRANT SELECT, INSERT, UPDATE ON profile_revision TO archive_app;
GRANT SELECT, INSERT ON profile_revision_field_value TO archive_app;
GRANT SELECT, INSERT ON profile_review_record TO archive_app;

GRANT USAGE, SELECT ON SEQUENCE authorization_document_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE authorization_record_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE guest_profile_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE profile_field_definition_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE profile_field_value_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE profile_revision_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE profile_revision_field_value_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE profile_review_record_id_seq TO archive_app;
