CREATE TABLE profile_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_profile_id BIGINT NOT NULL REFERENCES guest_profile(id),
    category VARCHAR(16) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    sha256 CHAR(64) NOT NULL,
    size_bytes BIGINT NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_photo_object_key UNIQUE (object_key),
    CONSTRAINT uq_profile_photo_profile_category_sort
        UNIQUE (guest_profile_id, category, sort_order),
    CONSTRAINT ck_profile_photo_category CHECK (category IN ('AVATAR', 'LIFE'))
);

CREATE UNIQUE INDEX uq_profile_photo_avatar_one
    ON profile_photo (guest_profile_id) WHERE category = 'AVATAR';
CREATE INDEX ix_profile_photo_profile ON profile_photo (guest_profile_id);

CREATE TABLE profile_revision_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_revision_id BIGINT NOT NULL REFERENCES profile_revision(id),
    category VARCHAR(16) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    sha256 CHAR(64) NOT NULL,
    size_bytes BIGINT NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_profile_revision_photo_category_sort
        UNIQUE (profile_revision_id, category, sort_order),
    CONSTRAINT ck_profile_revision_photo_category
        CHECK (category IN ('AVATAR', 'LIFE'))
);

CREATE INDEX ix_profile_revision_photo_revision
    ON profile_revision_photo (profile_revision_id);

CREATE FUNCTION reject_profile_photo_immutable_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profile_revision_photo_immutable
    BEFORE UPDATE OR DELETE ON profile_revision_photo
    FOR EACH ROW EXECUTE FUNCTION reject_profile_photo_immutable_mutation();

GRANT SELECT, INSERT, UPDATE, DELETE ON profile_photo TO archive_app;
GRANT SELECT, INSERT ON profile_revision_photo TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE profile_photo_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE profile_revision_photo_id_seq TO archive_app;
