-- 课程模块：合集、课程、视频分块上传会话。
--
-- 课程由后台上传，H5 端按合集浏览。口径是「列表可见、内容加锁」：免费用户能看到
-- 标题、封面、类型、时长这些元数据，正文 markdown 与视频播放地址要 VIP。
-- 门禁**不在库里**，落在服务层——同一个前缀下列表要放行、详情要拦，
-- 库只负责把内容存对，谁能看是应用的事。
--
-- 视频走 COS 分块上传（浏览器切片 → 后端中转 → COS Multipart Upload），
-- 凭据不出服务端。所以要一张会话表记住 uploadId 是哪个管理员开的：
-- uploadId 会随响应回到浏览器，只按它找会话的话，任何登录管理员都能往别人的上传里塞分块。

-- ==========================================================================
-- 合集
-- ==========================================================================

CREATE TABLE course_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    sort_order INT NOT NULL DEFAULT 0,
    -- 合集是后台可维护的实体，下线用 HIDDEN 而不是删行——见下方 GRANT 段的说明。
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 名字是运营口中的分类名，重名会让后台下拉框出现两个一样的选项。
    CONSTRAINT uq_course_collection_name UNIQUE (name),
    CONSTRAINT ck_course_collection_status CHECK (status IN ('ACTIVE', 'HIDDEN'))
);

COMMENT ON TABLE course_collection IS
    '课程合集（分类），后台可维护；下线用 status = HIDDEN，不删行';

-- 列表按运营指定的顺序展示，id 兜底保证顺序稳定。
CREATE INDEX ix_course_collection_order ON course_collection (sort_order, id);

-- ==========================================================================
-- 课程
-- ==========================================================================

CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT NOT NULL REFERENCES course_collection (id),
    -- 教材名称。
    title VARCHAR(120) NOT NULL,
    subtitle VARCHAR(200),
    summary VARCHAR(500),
    -- 讲师。
    author_name VARCHAR(64),
    content_type VARCHAR(16) NOT NULL,
    -- 图文与纯文本的正文存库不存 COS：正文只有几十 KB，放对象存储会让每次
    -- 打开课程多一次跨网络往返，而且备份与回滚都得跟着对象一起做。
    content_markdown TEXT,
    cover_object_key VARCHAR(1024),
    video_object_key VARCHAR(1024),
    video_duration_seconds INT,
    video_size_bytes BIGINT,
    video_content_type VARCHAR(128),
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMPTZ,
    created_by_admin_id BIGINT REFERENCES admin_user (id),
    updated_by_admin_id BIGINT REFERENCES admin_user (id),
    -- 乐观锁，与 guest_profile / payment_order 同一套做法：两个运营同时改一节课，
    -- 后保存的那个必须撞 409 而不是静默覆盖。
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_course_content_type CHECK (content_type IN ('ARTICLE', 'VIDEO', 'TEXT')),
    CONSTRAINT ck_course_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    -- 三种类型对「内容」的要求不同。写进库里是因为服务层的校验不是唯一防线：
    -- 一节没有正文的图文课发布出去，用户点开就是一片空白，而且是付费内容。
    -- 判「有正文」用「至少一个非空白字符」而不是 btrim：编辑器清空后常留下一个换行，
    -- 而 Postgres 的 btrim 默认只去空格、不去换行与制表符。
    CONSTRAINT ck_course_content CHECK (
        (content_type IN ('ARTICLE', 'TEXT')
            AND content_markdown IS NOT NULL
            AND content_markdown ~ '[^[:space:]]')
        OR (content_type = 'VIDEO' AND video_object_key IS NOT NULL)
    ),
    -- 上架时间既是列表排序键也是「什么时候开始对外可见」的凭据，
    -- 已发布却没有它，H5 端就排不出顺序。
    CONSTRAINT ck_course_published_at CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL),
    -- 数据合理性兜底：0 秒或负数只可能是前端算错了。
    -- **这不是 5–15 分钟那类业务约束**——时长只登记、只展示，不参与任何校验，
    -- 也不产生任何提示，允许为空。库里关于时长的规则仅此一条。
    CONSTRAINT ck_course_duration CHECK (
        video_duration_seconds IS NULL OR video_duration_seconds > 0),
    -- 同上，字节数为 0 的视频不存在，只会是分块统计写错了。
    CONSTRAINT ck_course_video_size CHECK (video_size_bytes IS NULL OR video_size_bytes > 0)
);

COMMENT ON TABLE course IS
    '课程（教材名称等登记信息都在这张表）；正文存库，封面与视频存 COS';

-- 后台与 H5 都是「按合集列课程」，顺序由运营指定。
CREATE INDEX ix_course_in_collection_order ON course (collection_id, sort_order, id);

-- H5 首页与「最新上架」按发布时间倒序取已发布的课。
CREATE INDEX ix_course_status_published ON course (status, published_at DESC);

-- 一个视频对象只能挂在一节课上：分块上传完成后 objectKey 就归那节课，
-- 两条课程指向同一个 key 会让「删课顺手清对象」变成误删另一节课的视频。
CREATE UNIQUE INDEX uq_course_video_object_key ON course (video_object_key)
    WHERE video_object_key IS NOT NULL;

-- ==========================================================================
-- 视频分块上传会话
-- ==========================================================================

CREATE TABLE course_video_upload (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- COS 返回的 uploadId。续传与 complete 都靠它定位，重复即是串号。
    upload_id VARCHAR(256) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    -- 谁开的会话谁才能续传，见文件头的说明。
    admin_id BIGINT NOT NULL REFERENCES admin_user (id),
    original_filename VARCHAR(255),
    content_type VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'IN_PROGRESS',
    -- 浏览器在初始化时声明总大小，用来算出「哪一块是末块」：
    -- COS 要求非末块不小于 1 MiB，而单看一次请求是判断不出末块的。
    declared_total_bytes BIGINT,
    uploaded_bytes BIGINT NOT NULL DEFAULT 0,
    part_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_course_video_upload_id UNIQUE (upload_id),
    -- 一个对象键同时被两个会话写，先 complete 的那个会被后一个覆盖。
    CONSTRAINT uq_course_video_upload_object_key UNIQUE (object_key),
    CONSTRAINT ck_course_video_upload_status CHECK (
        status IN ('IN_PROGRESS', 'COMPLETED', 'ABORTED'))
);

COMMENT ON TABLE course_video_upload IS
    'COS 分块上传会话；临时数据，complete 或 abort 之后只留痕';

-- 后台要能看「我还有哪些没传完的」。
CREATE INDEX ix_course_video_upload_admin ON course_video_upload (admin_id, status, id DESC);

-- ==========================================================================
-- 运行时账号授权
-- ==========================================================================

-- course_collection 不给 DELETE：合集下挂着课程，删了会留孤儿；
-- 下线走 status = 'HIDDEN'。course 与 course_video_upload 给 DELETE：
-- 草稿写错要能删掉重来，上传会话本身就是临时数据。
GRANT SELECT, INSERT, UPDATE ON course_collection TO archive_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON course TO archive_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON course_video_upload TO archive_app;

-- V1 里那句 GRANT ... ON ALL SEQUENCES 只覆盖它执行时已存在的序列，
-- 后建的表必须自己再授一次，否则 IDENTITY 列取不到值，每一次插入都权限报错。
GRANT USAGE, SELECT ON SEQUENCE
    course_collection_id_seq, course_id_seq, course_video_upload_id_seq
    TO archive_app;

-- ==========================================================================
-- 种子数据
-- ==========================================================================

-- 产品定稿的四个分类。ON CONFLICT 让这段可重入：合集是后台可维护的实体，
-- 运营改过名字之后重跑迁移不该把它改回来，也不该撞唯一约束。
INSERT INTO course_collection (name, description, sort_order) VALUES
    ('情绪与认知', '识别情绪与认知偏差，先把自己看清楚', 10),
    ('择偶与筛选', '把标准说清楚，把人看明白', 20),
    ('恋爱关系', '关系里的相处、沟通与经营', 30),
    ('形象与状态', '外在形象与内在状态的日常管理', 40)
ON CONFLICT (name) DO NOTHING;
