-- 线上微信支付路径与会员等级体系。
-- 手动路径（管理员登记 → 邀请码 → 激活）保持原样，本迁移只放宽为线上路径必需的约束，
-- 并用 registration_channel / payment_channel 的 CHECK 约束把原有不变量按渠道重新固定。

ALTER TABLE user_account
    ADD COLUMN membership_tier VARCHAR(16) NOT NULL DEFAULT 'VIP',
    ADD COLUMN membership_credit_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN registration_channel VARCHAR(24) NOT NULL DEFAULT 'ADMIN_MANUAL';

ALTER TABLE user_account
    ALTER COLUMN created_by_admin_id DROP NOT NULL;

ALTER TABLE user_account
    ADD CONSTRAINT ck_user_account_membership_tier
        CHECK (membership_tier IN ('VIP', 'SVIP')),
    ADD CONSTRAINT ck_user_account_membership_credit
        CHECK (membership_credit_minor >= 0),
    ADD CONSTRAINT ck_user_account_registration_channel
        CHECK (registration_channel IN ('ADMIN_MANUAL', 'WECHAT_ONLINE')),
    ADD CONSTRAINT ck_user_account_manual_creator
        CHECK (registration_channel <> 'ADMIN_MANUAL' OR created_by_admin_id IS NOT NULL);

ALTER TABLE payment_record
    ADD COLUMN payment_channel VARCHAR(24) NOT NULL DEFAULT 'MANUAL',
    ADD COLUMN out_trade_no VARCHAR(64),
    ADD COLUMN transaction_id_ciphertext BYTEA,
    ADD COLUMN transaction_id_hmac VARCHAR(64),
    ADD COLUMN paid_amount_minor BIGINT,
    ADD COLUMN membership_credit_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN registered BOOLEAN NOT NULL DEFAULT FALSE;

-- 线上支付在账号建立之前就已完成，因此付款记录先落库、注册时再回填账号。
ALTER TABLE payment_record
    ALTER COLUMN user_account_id DROP NOT NULL,
    ALTER COLUMN operator_admin_id DROP NOT NULL;

ALTER TABLE payment_record
    ADD CONSTRAINT ck_payment_record_channel
        CHECK (payment_channel IN ('MANUAL', 'WECHAT_JSAPI')),
    ADD CONSTRAINT uq_payment_record_out_trade_no UNIQUE (out_trade_no),
    ADD CONSTRAINT ck_payment_record_manual_shape CHECK (
        payment_channel <> 'MANUAL'
        OR (user_account_id IS NOT NULL
            AND operator_admin_id IS NOT NULL
            AND out_trade_no IS NULL
            AND transaction_id_ciphertext IS NULL
            AND transaction_id_hmac IS NULL)
    ),
    ADD CONSTRAINT ck_payment_record_online_shape CHECK (
        payment_channel <> 'WECHAT_JSAPI'
        OR (operator_admin_id IS NULL
            AND out_trade_no IS NOT NULL
            AND payment_reference = out_trade_no
            AND paid_amount_minor IS NOT NULL
            AND transaction_id_ciphertext IS NOT NULL
            AND transaction_id_hmac IS NOT NULL)
    ),
    ADD CONSTRAINT ck_payment_record_registered_account
        CHECK (NOT registered OR user_account_id IS NOT NULL),
    ADD CONSTRAINT ck_payment_record_membership_credit CHECK (
        membership_credit_minor >= 0 AND membership_credit_minor <= amount_minor
    );

CREATE UNIQUE INDEX uq_payment_record_transaction_id
    ON payment_record (transaction_id_hmac)
    WHERE transaction_id_hmac IS NOT NULL;

CREATE TABLE wechat_payment_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    out_trade_no VARCHAR(64) NOT NULL,
    openid_ciphertext BYTEA NOT NULL,
    openid_hmac VARCHAR(64) NOT NULL,
    description VARCHAR(127) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    prepay_id VARCHAR(64),
    transaction_id_ciphertext BYTEA,
    transaction_id_hmac VARCHAR(64),
    presented_authorization_document_id BIGINT NOT NULL,
    payment_record_id BIGINT,
    paid_amount_minor BIGINT,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_wechat_payment_order_out_trade_no UNIQUE (out_trade_no),
    CONSTRAINT fk_wechat_payment_order_document FOREIGN KEY (presented_authorization_document_id)
        REFERENCES authorization_document (id),
    CONSTRAINT fk_wechat_payment_order_payment FOREIGN KEY (payment_record_id)
        REFERENCES payment_record (id),
    CONSTRAINT ck_wechat_payment_order_status
        CHECK (status IN ('CREATED', 'PAID', 'CLOSED', 'REFUNDED')),
    CONSTRAINT ck_wechat_payment_order_amount CHECK (amount_minor > 0),
    CONSTRAINT ck_wechat_payment_order_currency CHECK (currency = 'CNY'),
    CONSTRAINT ck_wechat_payment_order_settlement CHECK (
        (status IN ('CREATED', 'CLOSED')
            AND paid_at IS NULL
            AND paid_amount_minor IS NULL
            AND payment_record_id IS NULL
            AND transaction_id_ciphertext IS NULL
            AND transaction_id_hmac IS NULL)
        OR (status IN ('PAID', 'REFUNDED')
            AND paid_at IS NOT NULL
            AND paid_amount_minor IS NOT NULL
            AND payment_record_id IS NOT NULL
            AND transaction_id_ciphertext IS NOT NULL
            AND transaction_id_hmac IS NOT NULL)
    )
);

CREATE INDEX ix_wechat_payment_order_openid
    ON wechat_payment_order (openid_hmac, created_at DESC);

CREATE UNIQUE INDEX uq_wechat_payment_order_transaction_id
    ON wechat_payment_order (transaction_id_hmac)
    WHERE transaction_id_hmac IS NOT NULL;

CREATE TABLE registration_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hmac VARCHAR(64) NOT NULL,
    wechat_payment_order_id BIGINT NOT NULL,
    out_trade_no VARCHAR(64) NOT NULL,
    openid_ciphertext BYTEA NOT NULL,
    openid_hmac VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'UNUSED',
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    user_account_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_registration_token_hmac UNIQUE (token_hmac),
    CONSTRAINT fk_registration_token_order FOREIGN KEY (wechat_payment_order_id)
        REFERENCES wechat_payment_order (id),
    CONSTRAINT fk_registration_token_account FOREIGN KEY (user_account_id)
        REFERENCES user_account (id),
    CONSTRAINT ck_registration_token_status
        CHECK (status IN ('UNUSED', 'USED', 'EXPIRED')),
    CONSTRAINT ck_registration_token_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_registration_token_consumption CHECK (
        (status = 'USED' AND used_at IS NOT NULL AND user_account_id IS NOT NULL)
        OR (status <> 'USED' AND used_at IS NULL AND user_account_id IS NULL)
    )
);

-- 一个支付订单同时最多只有一个待用令牌；重新签发前必须先作废旧令牌。
CREATE UNIQUE INDEX uq_registration_token_unused_order
    ON registration_token (wechat_payment_order_id)
    WHERE status = 'UNUSED';

CREATE INDEX ix_registration_token_expiry
    ON registration_token (expires_at)
    WHERE status = 'UNUSED';

-- 历史手动登记的付款金额同样计入 SVIP 累计额度。等级阈值属于应用配置，
-- 因此这里只回填与阈值无关的累计额度，等级由 MembershipService 读取时对齐。
UPDATE payment_record
SET membership_credit_minor = amount_minor
WHERE payment_channel = 'MANUAL' AND status = 'PAID';

UPDATE user_account
SET membership_credit_minor = credited.total
FROM (
    SELECT user_account_id, SUM(membership_credit_minor) AS total
    FROM payment_record
    WHERE user_account_id IS NOT NULL
    GROUP BY user_account_id
) AS credited
WHERE user_account.id = credited.user_account_id;

GRANT SELECT, INSERT, UPDATE ON wechat_payment_order TO archive_app;
GRANT SELECT, INSERT, UPDATE ON registration_token TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE wechat_payment_order_id_seq TO archive_app;
GRANT USAGE, SELECT ON SEQUENCE registration_token_id_seq TO archive_app;
